/*
Abu H Rokon
Manager, Enterprise Application Architecture
Host Hotels & Resorts
2015
*/

package FTP_Helper;


import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;




public class FTP extends javax.swing.JFrame {
    private Object myFile;

   
    
    public FTP() {
        initComponents();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdditionalInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTrans = new javax.swing.JLabel();
        lblFiles = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFreq = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblJob = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblVndrTrans = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblVndrData = new javax.swing.JLabel();
        pnlDestination = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDest1 = new javax.swing.JTextField();
        btnDest1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDest2 = new javax.swing.JTextField();
        btnDest2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDest3 = new javax.swing.JTextField();
        btnDest3 = new javax.swing.JButton();
        pnlSource = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        btnSource = new javax.swing.JButton();
        pnlArchive = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtArch = new javax.swing.JTextField();
        btnArch = new javax.swing.JButton();
        pnlList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProcess = new javax.swing.JList();
        pnlStart = new javax.swing.JPanel();
        listSelector = new javax.swing.JComboBox();
        btnResetAll = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnHistory = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuResetAll = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FTP Helper");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        pnlAdditionalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlAdditionalInfo.setName(""); // NOI18N

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Files:");

        lblFiles.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Transmission Frequency");

        lblFreq.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("SQL JOB/SSIS Project");

        lblJob.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Email Notification");

        lblEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Vendor Contact (Transmission)");

        lblVndrTrans.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Vendor Contact (Data)");

        lblVndrData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlAdditionalInfoLayout = new javax.swing.GroupLayout(pnlAdditionalInfo);
        pnlAdditionalInfo.setLayout(pnlAdditionalInfoLayout);
        pnlAdditionalInfoLayout.setHorizontalGroup(
            pnlAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                .addGroup(pnlAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdditionalInfoLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFreq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVndrTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                                .addGroup(pnlAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVndrData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlAdditionalInfoLayout.setVerticalGroup(
            pnlAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdditionalInfoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJob, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVndrTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVndrData, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDestination.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Destination Folder # 1");

        txtDest1.setEditable(false);

        btnDest1.setText("Open");
        btnDest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDest1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Destination Folder # 2");

        txtDest2.setEditable(false);

        btnDest2.setText("Open");
        btnDest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDest2ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Destination Folder # 3");

        txtDest3.setEditable(false);

        btnDest3.setText("Open");
        btnDest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDest3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDestinationLayout = new javax.swing.GroupLayout(pnlDestination);
        pnlDestination.setLayout(pnlDestinationLayout);
        pnlDestinationLayout.setHorizontalGroup(
            pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(pnlDestinationLayout.createSequentialGroup()
                        .addComponent(txtDest1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDest1))
                    .addComponent(jLabel4)
                    .addGroup(pnlDestinationLayout.createSequentialGroup()
                        .addComponent(txtDest2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDest2))
                    .addComponent(jLabel8)
                    .addGroup(pnlDestinationLayout.createSequentialGroup()
                        .addComponent(txtDest3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDest3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDestinationLayout.setVerticalGroup(
            pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDest1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDest2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDest3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlSource.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Source ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Source Folder");

        txtSource.setEditable(false);

        btnSource.setText("Open");
        btnSource.setMaximumSize(new java.awt.Dimension(45, 25));
        btnSource.setMinimumSize(new java.awt.Dimension(45, 25));
        btnSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSourceLayout = new javax.swing.GroupLayout(pnlSource);
        pnlSource.setLayout(pnlSourceLayout);
        pnlSourceLayout.setHorizontalGroup(
            pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSourceLayout.createSequentialGroup()
                        .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSourceLayout.setVerticalGroup(
            pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlArchive.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Archive", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Archive Folder");

        txtArch.setEditable(false);

        btnArch.setText("Open");
        btnArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArchiveLayout = new javax.swing.GroupLayout(pnlArchive);
        pnlArchive.setLayout(pnlArchiveLayout);
        pnlArchiveLayout.setHorizontalGroup(
            pnlArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlArchiveLayout.createSequentialGroup()
                        .addComponent(txtArch, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArchiveLayout.setVerticalGroup(
            pnlArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchiveLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArch))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Processes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        listProcess.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        listProcess.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listProcess.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        listProcess.setName("listProcess"); // NOI18N
        listProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProcessMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listProcess);

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlStart.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        listSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Brand", "Benjamin West", "Concur", "HR Benefits", "Marriott", "Online Rewards", "Ritz Carlton", "Ramsey", "Smith Travel Research", "Starwood", " " }));
        listSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSelectorActionPerformed(evt);
            }
        });

        btnResetAll.setText("Reset All");
        btnResetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAllActionPerformed(evt);
            }
        });

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });

        btnHistory.setText("Transfer History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStartLayout = new javax.swing.GroupLayout(pnlStart);
        pnlStart.setLayout(pnlStartLayout);
        pnlStartLayout.setHorizontalGroup(
            pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStartLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(listSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetAll)
                .addGap(18, 18, 18)
                .addComponent(btnHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStartLayout.setVerticalGroup(
            pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetAll)
                    .addComponent(listSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        mnuResetAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        mnuResetAll.setText("Reset All");
        mnuResetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuResetAllActionPerformed(evt);
            }
        });
        jMenu1.add(mnuResetAll);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, 0));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDestination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlSource, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlArchive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlAdditionalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlArchive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlAdditionalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public FTP (String blank){
        } 
    
   
    
    
    private void listSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSelectorActionPerformed
         
        String[]  prcBlank = {""};
        String[]  prcMarriott  = {"Mercury", "A&C- Send File", "A&C - Receive File", "BI Monthly Weekly", "BI Owner Extract", };
        String[]  prcStarwood  = {"BI/MRI International", "BI/MRI", "Starwood JV Trial Balances", "Starwood Capex", "Starwood JV Assets"};
        String[]  prcConcur  = {"Concur Upload", "Concur Download"};
        String[]  prcHRBenefits = {"VSP Benefits Feed", "MetLife Benefits Feed"};
        String[]  prcBenWest = {"Benjamin West"};
        String[]  prcOnlineRewards = {"Rewards Upload", "Rewards Download"};
        String[]  prcRamsey = {"Ramsey Down"};
        String[]  prcRitz = {"Ritz Carlton Upload", "Ritz Carlton Download"};
        
        
        
        
        if (evt.getSource()== listSelector){
            JComboBox cb = (JComboBox)evt.getSource();
            String msg = (String)cb.getSelectedItem();

            switch (msg){
                case "Select a Brand":
                    listProcess.removeAll();
                    listProcess.setListData(prcBlank);
                break;
                case "Marriott":
                    listProcess.removeAll();
                    listProcess.setListData(prcMarriott);
                    break;
                case "Starwood":
                    listProcess.removeAll();
                    listProcess.setListData(prcStarwood);
                    break;
                case "Concur": 
                    listProcess.removeAll();
                    listProcess.setListData(prcConcur);
                    break;
                case "HR Benefits": 
                    listProcess.removeAll();
                    listProcess.setListData(prcHRBenefits);
                    break;
                case "Benjamin West": 
                    listProcess.removeAll();
                    listProcess.setListData(prcBenWest);
                    break;    
                case "Online Rewards": 
                    listProcess.removeAll();
                    listProcess.setListData(prcOnlineRewards);
                    break;   
                case "Ramsey": 
                    listProcess.removeAll();
                    listProcess.setListData(prcRamsey);
                    break; 
                case "Ritz Carlton":
                    listProcess.removeAll();
                    listProcess.setListData(prcRitz);
                default: txtSource.setText("Select an option");
                    
            }
        }
        
    }//GEN-LAST:event_listSelectorActionPerformed

    

    
    private void mnuResetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuResetAllActionPerformed
        // TODO add your handling code here:
        String[]    empty = {""};
        listProcess.setListData(empty);
        //listSelector.setModel("");
        listSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Brand", "Benjamin West", "Concur", "HR Benefits", "Marriott", "Online Rewards", "Ritz Carlton", "Ramsey", "Smith Travel Research", "Starwood", " " }));
        txtSource.setText("");
        txtDest1.setText("");
        txtDest2.setText("");
        txtDest3.setText("");
        txtArch.setText("");
        lblFiles.setText("");
        lblFreq.setText("");
        lblJob.setText("");
        lblEmail.setText("");
        lblVndrTrans.setText("");
        lblVndrData.setText("");
        Query.QueryString("");
    }//GEN-LAST:event_mnuResetAllActionPerformed

    private void listProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProcessMouseClicked
                
        if (evt.getSource()== listProcess){
            JList listSelect = (JList)evt.getSource();
            String prcSelector = (String)listSelect.getSelectedValue();            
            switch (prcSelector){
                
// These are individual processes within each brand/vendors to show source/destination
// folders as well as filenames/emails/frequency etc. 
                
        //Blank
                case "Select a Brand":
                    txtSource.setText("");
                    txtDest1.setText("");
                    txtDest2.setText("");
                    txtDest3.setText("");
                    txtArch.setText("");  
                    lblFiles.setText("");
                    lblFreq.setText("");
                    lblJob.setText("");
                    lblEmail.setText("");
                    lblVndrTrans.setText("");
                    lblVndrData.setText("");
                    Query.QueryString("");
                    break;                  
        
        //Marriott
                case "BI Owner Extract":
                    txtSource.setText("\\\\hhrhub1\\eclipse");
                    txtDest1.setText("\\\\hqbiprod\\Data Import\\P and L\\Backup MI Files");
                    txtDest2.setText("\\\\hqbiprod\\Data Import\\P and L\\Backup Ritz Files");
                    txtDest3.setText("\\\\hqbiprod\\Data Import\\Backup Intl\\MI Intl");
                    txtArch.setText("This file is not being archived.");  
                    lblFiles.setText("<html>PLE_121_*.txt<br/>PLA_121_*.txt<br/>BSE_121_*.txt</html>");
                    lblFreq.setText("Monthly - 1st");
                    lblJob.setText("MI_FTP_FilesLoad");
                    lblEmail.setText("<html>joanne.ballin@hosthotels.com<br/>jennifer.roberts@hosthotels.com<br/>brandeis.mitchell@hosthotels.com</html>");
                    lblVndrTrans.setText("<html>Michael.Coplin@marriott.com<br/>Jeffrey.Golding@marriott.com</html>");
                    lblVndrData.setText("denise.hughes@marriott.com");
                    Query.QueryString("");
                    break;
        //Ben West    
                case "Benjamin West":
                    txtSource.setText("\\\\hhrhub1\\ben_west\\");
                    txtDest1.setText("\\\\hqdata\\Peoplesoft\\Interfaces\\fs9prod\\tmp\\nac\\");
                    txtDest2.setText("None");
                    txtDest3.setText("None");
                    txtArch.setText("This file is not being archived.");  
                    lblFiles.setText("<html>Not Defined</html>");
                    lblFreq.setText("Not Defined");
                    lblJob.setText("PSFTPFILEMOVES on HQPSDEV");
                    lblEmail.setText("<html>brandeis.mitchell@hosthotels.com<br/>lisa.schatz@hosthotels.com<br/>karen.brandt@hosthotels.com<br/>tina.fox@hosthotels.com<br/></html>");
                    lblVndrTrans.setText("<html>Not Defined</html>");
                    lblVndrData.setText("Not Defined");
                    Query.QueryString("");
                    Query.QueryString("Select * from BenWest Order by DateMoved Desc");
                    break;   
        //Metlife
                case "MetLife Benefits Feed":
                    txtSource.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\Interfaces\\Benefit Feeds\\");
                    txtDest1.setText("\\\\hhrhub1\\HR\\MetLife\\");
                    txtDest2.setText("None");
                    txtDest3.setText("None");
                    txtArch.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\History\\Benefit Feeds\\");  
                    lblFiles.setText("<html>hosthotel_denelig.dat</html>");
                    lblFreq.setText("Not Defined");
                    lblJob.setText("PSFTPFILEMOVES on HQPSDEV");
                    lblEmail.setText("<html>Brandeis.Mitchell@hosthotels.com<br/>leonid.geller@hosthotels.com<br/>mark.hatton@hosthotels.com<br/></html>");
                    lblVndrTrans.setText("<html>Not Defined</html>");
                    lblVndrData.setText("Not Defined");
                    Query.QueryString("");
                    Query.QueryString("Select * from MetLife Order by DateMoved Desc");
                    break;    
        //VSP
                case "VSP Benefits Feed":
                    txtSource.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\Interfaces\\Benefit Feeds\\");
                    txtDest1.setText("\\\\hhrhub1\\HR\\VSP\\");
                    txtDest2.setText("None");
                    txtDest3.setText("None");
                    txtArch.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\History\\Benefit Feeds\\");  
                    lblFiles.setText("<html>g0005459</html>");
                    lblFreq.setText("Not Defined");
                    lblJob.setText("PSFTPFILEMOVES on HQPSDEV");
                    lblEmail.setText("<html>Brandeis.Mitchell@hosthotels.com<br/>leonid.geller@hosthotels.com<br/>mark.hatton@hosthotels.com<br/></html>");
                    lblVndrTrans.setText("<html>Not Defined</html>");
                    lblVndrData.setText("Not Defined");
                    Query.QueryString("");
                    Query.QueryString("Select * from VSP Order by DateMoved Desc");

                    break;
        //Online Rewards Down
                case "Rewards Download":
                    txtSource.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\Interfaces\\OnlineRewards\\");
                    txtDest1.setText("\\\\hhrhub1\\rewards_down\\");
                    txtDest2.setText("None");
                    txtDest3.setText("None");
                    txtArch.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\History\\OnlineRewards\\");  
                    lblFiles.setText("<html>EmpOnlineRewards*.xls</html>");
                    lblFreq.setText("Daily");
                    lblJob.setText("PSFTPFILEMOVES on HQPSDEV");
                    lblEmail.setText("<html>Brandeis.Mitchell@hosthotels.com<br/>leonid.geller@hosthotels.com</html>");
                    lblVndrTrans.setText("<html>Not Defined</html>");
                    lblVndrData.setText("Not Defined");
                    Query.QueryString("");
                    Query.QueryString("Select * from OnlineRewards_Down Order by DateMoved Desc");
                    break;            
        //Online Rewards Upload
                case "Rewards Upload":
                    txtSource.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\Interfaces\\OnlineRewards\\");
                    txtDest1.setText("\\\\hhrhub1\\rewards_Up\\");
                    txtDest2.setText("None");
                    txtDest3.setText("None");
                    txtArch.setText("\\\\hqdata\\Peoplesoft\\reports\\hr92prod\\History\\OnlineRewards\\");  
                    lblFiles.setText("<html>EmpOnlineRewards*.xls</html>");
                    lblFreq.setText("Daily");
                    lblJob.setText("PSFTPFILEMOVES on HQPSDEV");
                    lblEmail.setText("<html>Brandeis.Mitchell@hosthotels.com<br/>leonid.geller@hosthotels.com</html>");
                    lblVndrTrans.setText("<html>Not Defined</html>");
                    lblVndrData.setText("Not Defined");
                    Query.QueryString("");
                    Query.QueryString("Select * from OnlineRewards_Up Order by DateMoved Desc");
                    break;

        //Ramsey 
                case "Ramsey Down":
                    txtSource.setText("\\\\hhrhub1\\ramsey\\");
                    txtDest1.setText("\\\\hqdata\\Peoplesoft\\Interfaces\\fs9prod\\tmp\\nac\\");
                    txtDest2.setText("None");
                    txtDest3.setText("None");
                    txtArch.setText("This file is not being archived.");  
                    lblFiles.setText("<html>Not Defined</html>");
                    lblFreq.setText("Not Defined");
                    lblJob.setText("PSFTPFILEMOVES on HQPSDEV");
                    lblEmail.setText("<html>brandeis.mitchell@hosthotels.com<br/>lisa.schatz@hosthotels.com<br/>karen.brandt@hosthotels.com<br/>philip.lemburg@hosthotels.com<br/>kevin.notter@hosthotels.com<br/>winnie.tang@hosthotels.com</html>");
                    lblVndrTrans.setText("<html>Not Defined</html>");
                    lblVndrData.setText("Not Defined");
                    Query.QueryString("");
                    Query.QueryString("Select * from Ramsey Order by DateMoved Desc");
                    break;
        
        //Starwood            
                case "Starwood JV":
                    
                    txtSource.setText("\\\\hqdata\\peoplesoft\\Interfaces\\fs9prod\\tmp\\nac");
                    Query.QueryString("");
                    break;
        //Concur        
                case "Concur Upload":
                    txtSource.setText("\\\\hqdata\\peoplesoft\\Interfaces\\fs9prod\\tmp");
                    Query.QueryString("");
                    break;
                case "Concur Download":
                    txtSource.setText("\\\\hqdata\\peoplesoft\\Interfaces\\fs9prod");
                    txtDest1.setText("\\\\hqdata\\peoplesoft\\Interfaces\\fs9prod\\tmp\\nac");
                    Query.QueryString("");
                    break;
                   
                default:
                    txtSource.setText("");
                    txtDest1.setText("");
                    txtDest2.setText("");
                    txtDest3.setText("");
                    txtArch.setText("");  
                    lblFiles.setText("");
                    lblFreq.setText("");
                    lblJob.setText("");
                    lblEmail.setText("");
                    lblVndrTrans.setText("");
                    lblVndrData.setText("");
                    Query.QueryString("");
            }
            
            
        }
    }//GEN-LAST:event_listProcessMouseClicked

    private void btnSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSourceActionPerformed
        
        String srcPath = txtSource.getText(); // path to the directory to be opened
        String infoMessage = "Path not found. \nEither a process is not defined \nor you do not have sufficient permission.";
        File file = new File(srcPath);
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (Exception e){
                    JOptionPane.showMessageDialog(null, infoMessage + "\nDetails: "+ e, "Error!", JOptionPane.ERROR_MESSAGE);
                    
        }
    }//GEN-LAST:event_btnSourceActionPerformed

    private void btnDest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDest1ActionPerformed
        // TODO add your handling code here:
        String destPath = txtDest1.getText();
        String infoMessage = "Path not found. \nEither a process is not defined \nor you do not have sufficient permission.";
        File file = new File(destPath);
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (Exception e){
                    JOptionPane.showMessageDialog(null, infoMessage + "\nDetails: "+ e, "Error!", JOptionPane.ERROR_MESSAGE);
                    
        }
    }//GEN-LAST:event_btnDest1ActionPerformed

    private void btnArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchActionPerformed
        // TODO add your handling code here:
        String destArch = txtArch.getText();
        String infoMessage = "Path not found. \nEither a process is not defined \nor you do not have sufficient permission.";
        
        File file = new File(destArch);
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (Exception e){
                    JOptionPane.showMessageDialog(null, infoMessage + "\nDetails: "+ e, "Error!", JOptionPane.ERROR_MESSAGE);
                    
        }
    }//GEN-LAST:event_btnArchActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0x0);
        
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnResetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAllActionPerformed
        // TODO add your handling code here:
        
        String[]    empty = {""};
        listProcess.setListData(empty);
        //listSelector.removeAllItems();
        listSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Brand", "Benjamin West", "Concur", "HR Benefits", "Marriott", "Online Rewards", "Ritz Carlton", "Ramsey", "Smith Travel Research", "Starwood", " " }));
        txtSource.setText("");
        txtDest1.setText("");
        txtDest2.setText("");
        txtDest3.setText("");
        txtArch.setText("");
        lblFiles.setText("");
        lblFreq.setText("");
        lblJob.setText("");
        lblEmail.setText("");
        lblVndrTrans.setText("");
        lblVndrData.setText("");
        Query.QueryString("");
        /*
        if (evt.getSource()== btnResetAll.getKeyListeners()){
            JComboBox cb = (JComboBox)evt.getSource();
            String msg = (String)cb.getSelectedItem();
           }
        */
    }//GEN-LAST:event_btnResetAllActionPerformed

    private void btnDest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDest2ActionPerformed
        // TODO add your handling code here:
         
        String destPath = txtDest2.getText();
        String infoMessage = "Path not found. \nEither a process is not defined \nor you do not have sufficient permission.";
        File file = new File(destPath);
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (Exception e){
                    JOptionPane.showMessageDialog(null, infoMessage + "\nDetails: "+ e, "Oops!", JOptionPane.ERROR_MESSAGE);
                    
        }
    }//GEN-LAST:event_btnDest2ActionPerformed

    private void btnDest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDest3ActionPerformed
        // TODO add your handling code here:
        
        String destPath = txtDest3.getText();
        String infoMessage = "Path not found. \nEither a process is not defined \nor you do not have sufficient permission.";
        File file = new File(destPath);
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (Exception e){
                    JOptionPane.showMessageDialog(null, infoMessage + "\nDetails: "+ e, "Oops!", JOptionPane.ERROR_MESSAGE);
                    
        }
    }//GEN-LAST:event_btnDest3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "Host Hotels & Resorts\nFTP Process Helper\nAbu H Rokon, 2015", "About", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        String infoMessage = "No process selected or\nTransfer history doesn't exist";
        try {
        TableFromDatabase frame = new TableFromDatabase();
        setHistoryIcon();
        
        frame.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Favicon.gif")));
        frame.setTitle("File Transfer History");
        frame.setLocation(150,200);
        frame.pack();
        frame.setSize(new Dimension(1200,600));
        frame.setVisible(true);
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(null, infoMessage + "" + "", "Oops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHistoryActionPerformed


    public static void main(String args[]) {
     
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
     
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FTP().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArch;
    private javax.swing.JButton btnDest1;
    private javax.swing.JButton btnDest2;
    private javax.swing.JButton btnDest3;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnResetAll;
    private javax.swing.JButton btnSource;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFiles;
    private javax.swing.JLabel lblFreq;
    private javax.swing.JLabel lblJob;
    private javax.swing.JLabel lblTrans;
    private javax.swing.JLabel lblVndrData;
    private javax.swing.JLabel lblVndrTrans;
    private javax.swing.JList listProcess;
    private javax.swing.JComboBox listSelector;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuResetAll;
    private javax.swing.JPanel pnlAdditionalInfo;
    private javax.swing.JPanel pnlArchive;
    private javax.swing.JPanel pnlDestination;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlSource;
    private javax.swing.JPanel pnlStart;
    private javax.swing.JTextField txtArch;
    private javax.swing.JTextField txtDest1;
    private javax.swing.JTextField txtDest2;
    private javax.swing.JTextField txtDest3;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Favicon.gif")));
    }

    private void setHistoryIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Favicon.gif")));
    }
}
